name: Feature request
description: Suggest an idea
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What do you want to build?
      placeholder: Add AI scoring to backend...
    validations:
      required: true
